version: '3.7'
services:
    vpn:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: vpn
        restart: always
        environment:
            - ANYCONNECT_SERVER=s35.serspeed.info:555
            - ANYCONNECT_USER=myusername
            - ANYCONNECT_PASSWORD=mypassword
            - CERT=pin-sha256:x07xY+Y91ZMlunqWD7i8XBA8x7Rt/MS492ysTnRP46w=
            - ANYCONNECT_AUTH_TYPE=Basics
            - CHECK_WEBSITE=twitter.com
        stdin_open: true
        tty: true
        cap_add:
          - ALL
        privileged: true

        ports:
            - "1081:1081"
            - "3389:3389"